# Generated by Django 3.0.7 on 2020-07-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
