# Generated by Django 3.0.7 on 2020-06-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('ACCEPT', 'Accept'), ('CONFIRMED', 'Confirmed'), ('WAITING', 'Waiting'), ('READY', 'Ready'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=100),
        ),
    ]
