# Generated by Django 3.0.7 on 2020-06-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='owner',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
