# Generated by Django 3.0.7 on 2020-06-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200627_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ready',
        ),
    ]
