# Generated by Django 3.0.7 on 2020-06-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default-user.png', upload_to='profile_pics'),
        ),
    ]
