# Generated by Django 3.0.7 on 2020-07-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.FileField(default='default-user.png', upload_to='user_pics'),
        ),
    ]
